# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  my-workflow:
    jobs:
      - test

jobs:
  test:
    docker: 
      - image: node:21-slim
    steps:
      - checkout
      - run: npm i -g bun
      - run: bun install
      - run: bun run build
      - run: bun run test
