# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs: 
  bun: oven-sh/setup-bun@v1

workflows:
  my-workflow:
    jobs:
      - my-job

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
          name: Install bun
          command: bun install
      - run:
          name: Build
          command: bun run build
