# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  my-workflow:
    jobs:
      - my-job

jobs:
  my-job:
    executor: docker
    steps:
      - uses: circleci/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: oven-sh/setup-bun@v1
      - run:
          name: Install bun
          command: bun install
      - run:
          name: Build
          command: bun run build
