# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs: 
  node: circleci/node@5.1.0

workflows:
  my-workflow:
    jobs:
      - node/test
